# Generated by Django 3.2.6 on 2021-09-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
