# Generated by Django 3.2.6 on 2021-09-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(blank=True, null=True)),
                ('banner', models.ImageField(upload_to='banner')),
                ('logo', models.ImageField(upload_to='logo')),
            ],
        ),
    ]
